### PR TITLE
Add Timetable

### PR DESCRIPTION
**Pull request by LeoHerrmann**
[Timetable](https://github.com/LeoHerrmann/Timetable) was added to the list.

### CODE REVIEW

**Comment by mjswensen** [comment]
Hi @LeoHerrmann , it looks like the linked page (https://leoherrmann.github.io/Timetable/) no longer exists.

**Comment by LeoHerrmann** [comment]
Hi @mjswensen, thanks for pointing that out. I recently renamed all my repositories to lower case letters and it seems as if I forgot to make the according changes here as well. But now the broken link is fixed :)

**Comment by mjswensen** [comment]
Thanks @LeoHerrmann ! The app looks great by the way!

**Comment by LeoHerrmann** [comment]
Thank you very much, @mjswensen :D

**Pull request merged**
