### PR TITLE
adding travis.ci badge

### PR DESCRIPTION
**Pull request by evansantos**

### CODE REVIEW

**Comment by evansantos** [comment]
@hemanth had you enabled on travis to check if the pull requests are without any issue like 404?

**Comment by hemanth** [comment]
I have enabled Travis.

**Comment by hemanth** [comment]
[All is well](https://travis-ci.org/hemanth/awesome-pwa#L276) 👍

**Comment by evansantos** [comment]
@hemanth  silicon-valley-3o6EhWeei7wsp2jc1G

**Comment by hemanth** [comment]
siliconvalleyhbo-l46C4JfWleIDjtDJm

**Pull request merged**
