### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by TheW0LVERIN3**
Some basic sites that weren't in this yet

### CODE REVIEW

**Comment by mjswensen** [comment]
These look great except for Google Drive—can you verify that it is a PWA? (It may very well be but my browser didn't present the install option like it does for the others.)

**Comment by TheW0LVERIN3** [comment]
It does work. I used chrome. You just have to leave the tab open for a little while.

**Comment by mjswensen** [comment]
I left it open in [Brave](https://brave.com/mjs684) for about a half hour and still no dice, but I believe you 🙂

**Comment by TheW0LVERIN3** [comment]
image

**Comment by TheW0LVERIN3** [comment]
Screenshot 2020-10-31 140601

**Comment by TheW0LVERIN3** [comment]
Screenshot 2020-10-31 140601 (2)

**Pull request merged**
