### PR TITLE
Add three tutorials on PWA with VueJS

### PR DESCRIPTION
**Pull request by flavianh**

### CODE REVIEW

**Comment by flavianh** [comment]
Hi @hemanth, I don't know how to make the tests pass. Is there a vetting process or something like this? Do you need me for this PR's approval?

**Comment by hemanth** [comment]
It's nothing to do with your PR.

It's failing because of:

```
> Links 
  1. [L024]  https://anonymouschat.in Connection timed out - connect(2) for "anonymouschat.in" port 443 
  2. [L040]  https://meatscope.camera/ getaddrinfo: Name or service not known 
  3. [L106]  http://tech-blog.flipkart.net/2015/11/progressive-web-app/ getaddrinfo: Name or service not known 
```

**Comment by hemanth** [comment]
BWT do you have one link that has links to these 3 parter?

**Comment by flavianh** [comment]
Each part has links to the other parts. It's true that it's maybe too much to add 3 links :/. Plus it would avoid my doing another PR when parts 4-5-6 come out. What do think is the best way to go?

**Comment by flavianh** [comment]
@hemanth  Do you want me to delete these extra links in the PR ? You could have green tests that way

**Comment by hemanth** [comment]
Don't worry about the build, your PR is not breaking it, please reduce the number of links to 1.

**Comment by flavianh** [comment]
@hemanth Done, is it better?

**Pull request merged**
