### PR TITLE
README: Add Tender to PWA list

### PR DESCRIPTION
**Pull request by yolandaz**
https://tender.run/passkeys

### CODE REVIEW

**Comment by yolandaz** [comment]
@mjswensen bump on this PR! let me know if there's any changes I should make :)

**Comment by mjswensen** [comment]
Hi @yolandaz ,

Typically we link directly to the PWA itself, the link you provided is not a PWA:

image

Do you mind updating your link to point to `app.tender.run`?

(Also, side note for the `/passkeys` page you linked to in your comment:

> We're really focused on keeping our user's data secure and private, and passkeys just don't fit in that equation.

Based on the context of the page I think it's supposed to say "passwords" 🙂 )

**Comment by yolandaz** [comment]
@mjswensen link fixed! I just realized I linked the wrong page in the PR description - meant to link this one https://tender.run/web-app 😅

and thank you for pointing out the typo! i will get that fixed

**Comment by mjswensen** [comment]
Thanks @yolandaz !

**Pull request merged**
