### PR TITLE
Add Hyperdraft

### PR DESCRIPTION
**Pull request by rosano**
Notes app with ```[[wiki]]``` syntax for interlinking. Connect remoteStorage to publish as a website.

### CODE REVIEW

**Comment by mjswensen** [comment]
Does not appear to be a PWA:

image

**Comment by mjswensen** [comment]
@rosano , these apps that you've proposed look really awesome but they don't yet fit the PWA definition. I suspect that adding a manifest would get you 90% of the way there. If we can get more of the PWA checklist items above we'd be happy to add them to the list!

**Comment by rosano** [comment]
Added manifest.json https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fhyperdraft.rosano.ca%2F&strategy=mobile&category=pwa#pwa

Screen Shot 2020-12-28 at 12 54 18

**Comment by rosano** [comment]
@mjswensen I misunderstood 'manifest' as an outdated reference to the deprecated 'cache manifest'. They all have the manifest now.

There is a service worker at the `start_url` but this seems to not be reflected in Lighthouse. I'm not sure of the consequences of loading it on the homepage, which is usually JS-free.

Also the `start_url` is online, not sure why it doesn't pick that up.

**Pull request merged**
