### PR TITLE
add 2fA

### PR DESCRIPTION
**Pull request by crossphoton**

### CODE REVIEW

**Comment by mjswensen** [comment]
Hi @crossphoton , apologies for the delay on this.

I went to https://2fa.crossphoton.tech/ on my phone (in Brave browser for iOS as well as Safari) and all I get is a white screen. Is the site still up?

**Comment by crossphoton** [comment]
Hi Matt,
I've updates the project along with vulnerability updates.

Although I was not able to test much for iOS, so there might be issues with fingerprint scanning. I've tested using www.lambdatest.com for iPhone12 Safari (again fingerprint was not available in that, but at least there was no white screen).

Thanks for viewing this.

**Comment by mjswensen** [comment]
Thanks @crossphoton , looks good!

**Comment by mjswensen** [comment]
Merged manually due to conflicts.

**Pull request closed without merging**
